version: "3.9"

services:
  postgres_db:
    image: postgres:18
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kavinath@k17
      POSTGRES_DB: fullstackdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: kavinath/fastapi-backend:latest
    container_name: fastapi_backend
    depends_on:
      postgres_db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      POSTGRES_SERVER: postgres_db # hostname of postgres container
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kavinath@k17
      POSTGRES_DB: fullstackdb
      BACKEND_CORS_ORIGINS: '["http://54.226.141.154","http://localhost","http://localhost:5173"]'

  frontend:
    image: kavinath/fastapi-frontend:latest
    container_name: react_frontend
    restart: always
    depends_on:
      backend:
        condition: service_started
    ports:
      - "80:80"
    environment:
      VITE_API_URL: http://54.226.141.154:8000
      MAILCATCHER_HOST: http://localhost:1080

volumes:
  postgres_data:
